### ISSUE TITLE
intended form of zero in bitfields?

### ISSUE THREAD

**Issue by karlp** [eupn/stm32wb55#5]
Hi,

I'm porting some code that sets the characteristic event flags.  This is the following in C,
```C
/* Gatt Event Mask
 * Type of event generated by GATT server
 * See aci_gatt_add_char.
 */
#define GATT_DONT_NOTIFY_EVENTS                       0x00 
#define GATT_NOTIFY_ATTRIBUTE_WRITE                   0x01
#define GATT_NOTIFY_WRITE_REQ_AND_WAIT_FOR_APPL_RESP  0x02
#define GATT_NOTIFY_READ_REQ_AND_WAIT_FOR_APPL_RESP   0x04
```

In the rust package, it's a bitfield: https://github.com/eupn/stm32wb55/blob/master/src/command/gatt.rs#L1565

```rust
    pub struct CharacteristicEvent: u8 {
        const ATTRIBUTE_WRITE = 0x01;
        const CONFIRM_WRITE = 0x02;
        const CONFIRM_READ = 0x04;
    }
```

What's the "intended" way of writing this, when you want to use the "zero" form?  You can use a literal 0, but that's not as clear as the "CharacteristicEvent::NO_NOTIFY" or similar?

**Comment by karlp** [comment]
I've usd CharacteristicEvent::empty() but ... is that really the best way?

**Comment by eupn** [comment]
@karlp does this looks ok? https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=74f2593ee25960645b5d838d74db1640

**Comment by karlp** [comment]
sure! that's perfectly fine.  I didn't read up on bitfields enough toknow that the zeros could be put in them too, I'm pretty new to rust :)

**Comment by karlp** [comment]
Were you going to add this to the module? or just show how I could do it in general?  Should also apply to CharacteristicPermission as well?

Looking at AN5270 for ACI_GATT_ADD_CHAR, it should get 0s defined for CharacteristicProperty, CharacteristicPermission, CharacteristicEvent, 

For ACI_GATT_ADD_CHAR_DESC, there's 0, and some higher numbers missing from DescriptorPermission, AccessPermission

For ACI_GATT_UPDATE_CHAR_VALUE_EXT, the 0 should be added to UpdateType

I can make a PR for this is you'd prefer?

**Comment by eupn** [comment]
@karlp 

>I can make a PR for this is you'd prefer?

Sure, go ahead! That would be great!
